typography_spectrum: 0.2764172
color:
  saturation: 0.3095344
  lightness: 0.5399593
  brandStrength: 0.9657559
  brandColors:
    - '#FFFFFF'
    - '#161C15'
    - '#364D16'
    - '#BFC2CA'
    - '#B4A979'
  rhythmicContrast: 0.240783
layout_spectrum: 0.2462687
name: Rosso
title: Jake Xon
description: Blog
